<a href="https://colab.research.google.com/github/JuanpiMarinD/mineria-de-datos-MDJP/blob/main/Cuaderno.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Minería de Datos

## Primer Parcial

### Introducción

#### Conceptos

##### La minería de datos (Data Mining) es el proceso de descubrir patrones, tendencias y conocimientos significativos a partir de grandes conjuntos de datos. Combina métodos de estadísticas, inteligencia artificial y aprendizaje automático para analizar la información desde diferentes perspectivas y resumirla en información útil que puede ser usada para aumentar ingresos, reducir costos o ambas.


####Ciencia de Datos

##### La Ciencia de Datos y la Minería de Datos son campos estrechamente relacionados, pero con enfoques ligeramente diferentes. Mientras que la minería de datos se centra en descubrir patrones y conocimientos dentro de grandes conjuntos de datos, la ciencia de datos es un campo más amplio que abarca todo el ciclo de vida de los datos, desde la adquisición y limpieza hasta el análisis, modelado, interpretación y comunicación de resultados. En este contexto, la minería de datos puede considerarse una técnica fundamental utilizada dentro del marco más amplio de la ciencia de datos para extraer valor de los datos.

In [ ]:
def donothing(x):
  return x

# El comando magico %timeit sirve para evaluar el desempeño en terminos de tiempo
%timeit L = [n ** 2 for n in range(1000)]

84.9 µs ± 22.6 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [ ]:
# El comando magico %%timeit sirve también para evaluar el desempeño, solo que este abarca varias lineas de codigo en lugar de una
%%timeit
L = []
for n in range(1000):
  L.append(n ** 2)

85.1 µs ± 15.5 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [ ]:
%timeit?

In [ ]:
%%timeit?

IPython and Shell Commands

In [ ]:
!ls

sample_data


In [ ]:
%cd sample_data/

/content/sample_data


In [ ]:
%ls

anscombe.json*                mnist_test.csv
california_housing_test.csv   mnist_train_small.csv
california_housing_train.csv  README.md*


In [ ]:
!cat README.md

This directory includes a few sample datasets to get you started.

*   `california_housing_data*.csv` is California housing data from the 1990 US
    Census; more information is available at:
    https://docs.google.com/document/d/e/2PACX-1vRhYtsvc5eOR2FWNCwaBiKL6suIOrxJig8LcSBbmCbyYsayia_DvPOOBlXZ4CAlQ5nlDD8kTaIDRwrN/pub

*   `mnist_*.csv` is a small sample of the
    [MNIST database](https://en.wikipedia.org/wiki/MNIST_database), which is
    described at: http://yann.lecun.com/exdb/mnist/

*   `anscombe.json` contains a copy of
    [Anscombe's quartet](https://en.wikipedia.org/wiki/Anscombe%27s_quartet); it
    was originally described in

    Anscombe, F. J. (1973). 'Graphs in Statistical Analysis'. American
    Statistician. 27 (1): 17-21. JSTOR 2682899.

    and our copy was prepared by the
    [vega_datasets library](https://github.com/altair-viz/vega_datasets/blob/4f67bdaad10f45e3549984e17e1b3088c731503d/vega_datasets/_data/anscombe.json).


In [ ]:
%env

{'SHELL': '/bin/bash',
 'COLAB_JUPYTER_TRANSPORT': 'ipc',
 'CGROUP_MEMORY_EVENTS': '/sys/fs/cgroup/memory.events /var/colab/cgroup/jupyter-children/memory.events',
 'VM_GCE_METADATA_HOST': '169.254.169.253',
 'MODEL_PROXY_HOST': 'https://mp.kaggle.net',
 'HOSTNAME': 'd8f41672fbd5',
 'LANGUAGE': 'en_US',
 'TBE_RUNTIME_ADDR': '172.28.0.1:8011',
 'GCE_METADATA_TIMEOUT': '3',
 'COLAB_JUPYTER_IP': '172.28.0.12',
 'COLAB_LANGUAGE_SERVER_PROXY_ROOT_URL': 'http://172.28.0.1:8013/',
 'KMP_LISTEN_PORT': '6000',
 'TF_FORCE_GPU_ALLOW_GROWTH': 'true',
 'ENV': '/root/.bashrc',
 'PWD': '/',
 'COLAB_LANGUAGE_SERVER_PROXY_REQUEST_TIMEOUT': '30s',
 'TBE_EPHEM_CREDS_ADDR': '172.28.0.1:8009',
 'TBE_CREDS_ADDR': '172.28.0.1:8008',
 'COLAB_JUPYTER_TOKEN': '<hidden>',
 'LAST_FORCED_REBUILD': '20250623',
 'TCLLIBPATH': '/usr/share/tcltk/tcllib1.20',
 'COLAB_KERNEL_MANAGER_PROXY_HOST': '172.28.0.12',
 'UV_BUILD_CONSTRAINT': '',
 'COLAB_WARMUP_DEFAULTS': '1',
 'HOME': '/root',
 'LANG': 'en_US.UTF-8',
 'CLOUDSDK

In [ ]:
# Original C-like code (causes SyntaxError in Python):
# int result = 0;
# for (int i=0; i<100; i++){
#     result += i;
# }

# Correct Python code:
result = 0
for i in range(100):
    result += i

Understanding Data Types in Python

In [1]:
import numpy as np

In [2]:
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [3]:
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

In [4]:
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [5]:
np.array([1, 2, 3, 4], dtype='int')

array([1, 2, 3, 4])

In [6]:
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

NumPy Array Attributes

In [12]:
import numpy as np

In [13]:
np.random.seed(0)

In [14]:
x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array

In [15]:
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


In [16]:
print("dtype:", x3.dtype)

dtype: int64


In [17]:
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

itemsize: 8 bytes
nbytes: 480 bytes


Array Indexing: Accessing Single Elements

In [18]:
x1

array([5, 0, 3, 3, 7, 9])

In [23]:
x1[0] # Colocamos el indice del elemento a extraer, en este caso el primer elemento tienen el indice 0

np.int64(5)

In [20]:
x1[4]

np.int64(7)

In [24]:
x1[-1] # Nos regresa el ultimo elemeno del array

np.int64(9)

In [22]:
x1[-2]

np.int64(7)

In [25]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [26]:
x2[0,0]

np.int64(3)

In [27]:
x2[2,0]

np.int64(1)

In [28]:
x2[2,-1]

np.int64(7)

In [30]:
x2[0, 0] = 12 # Asignar un nuevo valor (12) al renglon 0 columna 0
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

#### Estadistica Basica

Media (Mean)

In [31]:
data = np.array([1, 2, 3, 4, 5])
media = np.mean(data)
print(media)

3.0


Promedio (Average) y Promedio Ponderado


In [32]:
data = np.array([1, 2, 3, 4, 5])
weights = np.array([1, 2, 3, 4, 5])
promedio = np.average(data)
promedio_ponderado = np.average(data, weights=weights)

In [34]:
print(promedio)
print(promedio_ponderado)

3.0
3.6666666666666665


Mediana

In [35]:
mediana = np.median(data)
print(mediana)

3.0


Varianza y Desviación Estándar

In [36]:
varianza = np.var(data)
desviacion = np.std(data)

In [38]:
print(varianza)
print(desviacion)

2.0
1.4142135623730951


Generación de Datos Aleatorios

In [41]:
muestra = np.random.normal(0, 1, 1000)
print(np.mean(muestra), np.std(muestra))

0.0024029618578246446 1.00901955868826


Correlación

In [42]:
corr = np.corrcoef([1,2,3], [1,5,7])
print(corr)

[[1.         0.98198051]
 [0.98198051 1.        ]]
